apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: payment-dev

namePrefix: dev-

components:
- ../../components/logging

replicas:
- name: payment-api
  count: 1

commonLabels:
  environment: development
