apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging
namePrefix: staging-

patchesJson6902:
- target:
    kind: Deployment
    name: webapp
  path: add-sidecar.yaml
- target:
    kind: Deployment
    name: webapp
  path: update-resources.yaml
