apiVersion: v1
kind: Service
metadata:
  name: payment-api
  labels:
    app: payment
    component: api
spec:
  selector:
    app: payment
    component: api
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
