apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: development

namePrefix: dev-

commonLabels:
  environment: dev
  team: dev-team

commonAnnotations:
  deployed-by: kustomize
  env-type: development

replicas:
- name: api
  count: 1
- name: redis
  count: 1

images:
- name: nginx
  newTag: "1.19-alpine"
- name: redis
  newTag: "6.0-alpine"
